### ISSUE TITLE
 Color banding for VGA output in Vertical screen mode

### ISSUE THREAD

**Issue by eskwadrat** [MiSTer-devel/Arcade-CrazyKong_MiSTer#4]
Color banding on VGA output when switched to vertical screen mode. Horizontal mode looks good. Confirmed on 3 different LCD monitors (Dell 20", Microtouch 15", Samsung 19") plus one CRT monitor (Viewsonic 17"). Per core developer feedback (Ash) it's most likely caused by bad timing (too short) for blanking signal (horizontal sync). That confuses the AGC circuits in most monitors, and causes that kind of banding. Similar issue observed for other arcade cores: burning rubber, catacomb, crazy kong, moon cresta, omega, pisces, pooyan, scramble, super glob.

**Comment by paulb-nl** [comment]
can be closed
